version: "3"
services:

  gateway:
    image: nginx:latest
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - order-service
      - order-db
      - stock-service
      - stock-db
      - payment-service
      - payment-db

  order-service:
    build: ./order
    image: order:latest
    environment:
      - USER_SERVICE_URL=http://gateway:80/payment
      - STOCK_SERVICE_URL=http://gateway:80/stock
    command: gunicorn -b 0.0.0.0:5000 app:app -w 1 --timeout 10
    env_file:
      - env/order_redis.env

  order-db:
    image: redis:latest
    command: redis-server --requirepass redis --maxmemory 512mb
    ports:
      - 8001:6379

  stock-service:
    build: ./stock
    image: stock:latest
    command: gunicorn -b 0.0.0.0:5000 app:app -w 1 --timeout 10
    env_file:
      - env/stock_redis.env

  stock-db:
    image: redis:latest
    command: redis-server --requirepass redis --maxmemory 512mb
    ports:
      - 8002:6379

  payment-service:
    build: ./payment
    image: user:latest
    command: gunicorn -b 0.0.0.0:5000 app:app -w 1 --timeout 10
    env_file:
      - env/payment_redis.env

  payment-db:
    image: redis:latest
    command: redis-server --requirepass redis --maxmemory 512mb
    ports:
      - 8003:6379
