apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: ClusterIP
  selector:
    component: order
  ports:
    - port: 5000
      name: http
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: order
  template:
    metadata:
      labels:
        component: order
    spec:
      containers:
        - name: order
          image: order:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: "128Mi"
              cpu: "1"
            requests:
              memory: "128Mi"
              cpu: "1"
          command: ["gunicorn"]
          args: ["-b", "0.0.0.0:5000", "app:app", "-w", "1", "--timeout", "120"]
          ports:
            - containerPort: 5000
          env:
            - name: USER_SERVICE_URL
              value: "http://user-service:5000"
            - name: STOCK_SERVICE_URL
              value: "http://stock-service:5000"
            - name: REDIS_HOST_0
              value: order-db-0-redis-master
            - name: REDIS_HOST_1
              value: order-db-1-redis-master
            - name: REDIS_HOST_2
              value: order-db-2-redis-master
            - name: REDIS_PORT
              value: '6379'
            - name: REDIS_PASSWORD
              value: "redis"
            - name: REDIS_DB
              value: "0"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: order-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order-deployment
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 60